apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 8.5.0
  auth:
    fileRealm:
    - secretName: de-filerealm-secret
  nodeSets:
  - name: default
    count: 1
    config:
      action.auto_create_index:  "+filebeat-*,+fluentbit-*,-index1,+ind*" 
      node.store.allow_mmap: false
