# apiVersion: v1
# kind: Secret
# metadata:
#   name: secret-basic-auth-elk
# type: kubernetes.io/basic-auth
# stringData:
#   username: de1
#   password: fbomal
#   roles: superuser

kind: Secret
apiVersion: v1
metadata:
  name: de-filerealm-secret
stringData:
  users: |-
    de1:$2a$10$xfkUJWUfFQpnh6crf05NiuT1FoCSPiOKyAGvU.lORHusHV7XhScZG
  users_roles: |-
    superuser:de1